// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/debug-report/:jobId": {
    params: {
      "jobId": string;
    };
  };
  "/app/generation-history": {
    params: {};
  };
  "/app/generation-history/:jobId": {
    params: {
      "jobId": string;
    };
  };
  "/app/additional": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/seo-tools": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/privacy": {
    params: {};
  };
  "/app/support": {
    params: {};
  };
  "/app/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/auth/login" | "/auth/*" | "/app" | "/app/debug-report/:jobId" | "/app/generation-history" | "/app/generation-history/:jobId" | "/app/additional" | "/app/onboarding" | "/app/seo-tools" | "/app/settings" | "/app/billing" | "/app/privacy" | "/app/support" | "/app/terms";
  };
  "routes/webhooks.customers.data_request.jsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.jsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.jsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/debug-report/:jobId" | "/app/generation-history" | "/app/generation-history/:jobId" | "/app/additional" | "/app/onboarding" | "/app/seo-tools" | "/app/settings" | "/app/billing" | "/app/privacy" | "/app/support" | "/app/terms";
  };
  "routes/app.debug-report.$jobId.jsx": {
    id: "routes/app.debug-report.$jobId";
    page: "/app/debug-report/:jobId";
  };
  "routes/app.generation-history.jsx": {
    id: "routes/app.generation-history";
    page: "/app/generation-history" | "/app/generation-history/:jobId";
  };
  "routes/app.generation-history.$jobId.jsx": {
    id: "routes/app.generation-history.$jobId";
    page: "/app/generation-history/:jobId";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.onboarding.jsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.seo-tools.jsx": {
    id: "routes/app.seo-tools";
    page: "/app/seo-tools";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.jsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.privacy.jsx": {
    id: "routes/app.privacy";
    page: "/app/privacy";
  };
  "routes/app.support.jsx": {
    id: "routes/app.support";
    page: "/app/support";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.terms.jsx": {
    id: "routes/app.terms";
    page: "/app/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.debug-report.$jobId": typeof import("./app/routes/app.debug-report.$jobId.jsx");
  "routes/app.generation-history": typeof import("./app/routes/app.generation-history.jsx");
  "routes/app.generation-history.$jobId": typeof import("./app/routes/app.generation-history.$jobId.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.jsx");
  "routes/app.seo-tools": typeof import("./app/routes/app.seo-tools.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.jsx");
  "routes/app.privacy": typeof import("./app/routes/app.privacy.jsx");
  "routes/app.support": typeof import("./app/routes/app.support.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.terms": typeof import("./app/routes/app.terms.jsx");
};